spring:
  profiles: peer1
  sleuth:
    sampler:
      percentage: 1
  kafka:
    bootstrap-servers: 10.170.185.49:9090
    producer:
      retries: 3
server:
  port: 8006
  id: ${spring.cloud.client.ipAddress}
  ip: ${spring.cloud.client.ipAddress}
---
spring:
  profiles: peer2
  sleuth:
    sampler:
    percentage: 1
  kafka:
    bootstrap-servers: 10.170.185.49:9090
    producer:
      retries: 3
server:
  port: 8007
  id: ${spring.cloud.client.ipAddress}
  ip: ${spring.cloud.client.ipAddress}