server:
  port: 8001
spring:
  application:
    name: micro-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/laohuaishu/micro-cloud-service
          basedir: config-repo
          #username: 2634113451@qq.com
          #password: xiao920616!@#