server:
  port: 7000
spring:
  application:
    name: micro-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/laohuaishu/micro-cloud-service/
          search-paths: config-repo/service-*-repo,config-repo/server-*-repo