spring:
  profiles: peer1
from: git-dev-1.1
server:
  port: 8000
  ip: 127.0.0.1
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
---
spring:
  profiles: peer2
  cloud:
      inetutils:
        ignored-interfaces[0]: eth0
from: git-dev-1.2
server:
  port: 8001
