spring:
  profiles: dev-peer01
  application:
      name: server-eureka
server:
  port: 7006
eureka:
  server:
    enable-self-preservation: true
  instance:
    app-group-name: server-eureka
    appname: server-eureka-peer01
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://10.171.91.140:7007/eureka/
    register-with-eureka: true
    fetch-registry: true
---
spring:
  profiles: dev-peer02
  application:
      name: server-eureka
server:
  port: 7007
eureka:
  server:
    enable-self-preservation: true
  instance:
    app-group-name: server-eureka
    appname: server-eureka-peer02
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://10.171.91.140:7006/eureka/
    register-with-eureka: true
    fetch-registry: true