spring:
  profiles: peer1
server:
  port: 7006
eureka:
  server:
    enable-self-preservation: false
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://101.200.87.36:7007/eureka/
---
spring:
  profiles: peer2
server:
  port: 7007
eureka:
  server:
    enable-self-preservation: false
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://101.200.87.36:7006/eureka/